#!python
#set filetype=python

import unittest
import argparse
from python_src.build_utils import build

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    build('all')

    test_loader = unittest.TestLoader()
    test_suite = test_loader.discover('integration_tests', pattern='*.py')

    test_runner = unittest.TextTestRunner(verbosity=2)
    result = test_runner.run(test_suite)



